// Generated by scripts/generate-css-variables-docs.mjs — do not edit by hand.

/**
 * Library routes that expose at least one CSS variable, i.e. the ones whose
 * `/styles/` tab has something to document. Headless libraries (a store, a
 * portal, a drag-and-drop utility) are absent, and their styles tab is marked
 * `noindex` so it never reaches the sitemap as an empty page.
 */
export const THEMEABLE_LIBRARY_ROUTES: ReadonlySet<string> = new Set([
	'action-sheet',
	'avatar',
	'badges',
	'board',
	'breadcrumbs',
	'buttons',
	'calendar',
	'forms',
	'icons',
	'loading',
	'metrics',
	'milestones',
	'modal',
	'nav',
	'paginable',
	'panels',
	'signature',
	'skeleton',
	'stepper',
	'toast',
	'utils'
]);
