#!/usr/bin/env node
/**
 * generate-version — stamp the docs app with the version it was built from, so a
 * deploy is verifiable at a glance in the nav footer.
 *
 * Reads the root package.json `version` and the current git short SHA + build
 * date, and writes them as a typed constant the app-shell consumes. Runs on
 * `prestart` / `prebuild`, so the deployed bundle always reflects the exact
 * commit that produced it (the CI/deploy runner regenerates it after checkout).
 *
 * Output: src/app/version.generated.ts
 * Run:    npm run generate:version
 */
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

/** Short commit SHA; falls back to `unknown` outside a git checkout. */
let commit = 'unknown';
try {
	commit = execSync('git rev-parse --short HEAD', { cwd: ROOT }).toString().trim();
} catch {
	// no git available (e.g. a source tarball) — keep the fallback
}

const builtAt = new Date().toISOString().slice(0, 10);

const output = `// Generated by scripts/generate-version.mjs — do not edit by hand.
export const APP_VERSION = {
	version: '${pkg.version}',
	commit: '${commit}',
	builtAt: '${builtAt}'
} as const;
`;

fs.writeFileSync(path.join(ROOT, 'src/app/version.generated.ts'), output);
console.log(`[version] ${pkg.version} · ${commit} · ${builtAt}`);
