/**
 * Self-hosts the documentation text fonts.
 *
 * Fetches the Google Fonts `css2` stylesheet for the families used by the app,
 * downloads every referenced `woff2` into `public/fonts/google/`, rewrites the
 * `@font-face` `src` URLs to the local `/fonts/google/` path and writes the
 * result to `src/styles/fonts.scss` (bundled and inlined by Beasties).
 *
 * Run on demand (NOT part of the build — it needs network access):
 *   npm run generate:fonts
 *
 * Update FONTS_CSS_URL when the family/weight set in src/index.html changes.
 */

import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/** Same family/weight set the app renders (keep in sync with the heading/body CSS). */
const FONTS_CSS_URL =
	'https://fonts.googleapis.com/css2?family=Sora:wght@600;700;800&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500;700&family=VT323&display=swap';

/** A modern desktop UA so the API returns woff2 (not ttf) instances. */
const USER_AGENT =
	'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const FONTS_DIR = 'public/fonts/google';
const SCSS_OUTPUT = 'src/styles/fonts.scss';

const HEADER = `/**
 * Self-hosted text fonts (Sora, Inter, JetBrains Mono, VT323).
 * GENERATED by scripts/generate-fonts.mjs — do not edit by hand.
 * woff2 files live in public/fonts/google/ and are served from /fonts/google/.
 * Regenerate with: npm run generate:fonts
 */
`;

/**
 * Fetches text content with the configured user agent.
 *
 * @param {string} url Resource URL.
 * @returns {Promise<string>} Response body as text.
 */
async function fetchText(url) {
	const response = await fetch(url, { headers: { 'User-Agent': USER_AGENT } });
	if (!response.ok) {
		throw new Error(`GET ${url} -> ${response.status}`);
	}
	return response.text();
}

/**
 * Downloads a binary resource to disk.
 *
 * @param {string} url Resource URL.
 * @param {string} destination Output path.
 */
async function download(url, destination) {
	const response = await fetch(url, { headers: { 'User-Agent': USER_AGENT } });
	if (!response.ok) {
		throw new Error(`GET ${url} -> ${response.status}`);
	}
	await writeFile(destination, Buffer.from(await response.arrayBuffer()));
}

/**
 * Generates the self-hosted font assets and stylesheet.
 */
async function main() {
	const css = await fetchText(FONTS_CSS_URL);
	const urls = [...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) ?? [])];

	if (urls.length === 0) {
		throw new Error('No woff2 URLs found in the Google Fonts response.');
	}

	// Reset the asset directory so removed subsets do not linger.
	await rm(FONTS_DIR, { recursive: true, force: true });
	await mkdir(FONTS_DIR, { recursive: true });

	for (const url of urls) {
		const basename = url.split('/').pop();
		await download(url, join(FONTS_DIR, basename));
	}

	const localCss = css.replace(/https:\/\/fonts\.gstatic\.com\/s\/[^)]*\/([^/)]+\.woff2)/g, '/fonts/google/$1');
	await writeFile(SCSS_OUTPUT, HEADER + localCss, 'utf8');

	const written = (await readdir(FONTS_DIR)).filter((name) => name.endsWith('.woff2'));
	console.log(`[fonts] ${written.length} woff2 files in ${FONTS_DIR}; @font-face written to ${SCSS_OUTPUT}.`);
}

main().catch((error) => {
	console.error('[generate-fonts] failed:', error);
	process.exit(1);
});
